services:
  # Local Ethereum node using Anvil
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: anvil
    environment:
      ANVIL_IP_ADDR: "0.0.0.0"
    working_dir: /anvil
    ports:
      - "8545:8545"
    command: anvil

  # Frontend development server
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_RPC_URL=http://localhost:8545
      - VITE_CHAIN_ID=31337
